# catalog-info.yaml

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-app
spec:
  type: service
  lifecycle: production
  owner: team-j
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: jsonplaceholder-posts
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition: |
    openapi: 3.0.0
    info:
      title: JSONPlaceholder Posts API
      version: 1.0.0
    paths:
      /posts:
        get:
          summary: Get all posts
