apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: currencycloud-auth-login
  description: CurrencyCloud Login API using formData (login_id + api_key)
  tags:
    - auth
    - rest
    - currencycloud
spec:
  type: openapi
  lifecycle: production
  owner: your-team
  definition: |
    openapi: 3.0.0
    info:
      title: CurrencyCloud Login API
      version: 1.0.0
      description: |
        This API allows users to authenticate to CurrencyCloud using `login_id` and `api_key`.
    servers:
      - url: https://devapi.currencycloud.com
    paths:
      /v2/authenticate/api:
        post:
          summary: Authenticate via login_id and api_key
          requestBody:
            required: true
            content:
              application/x-www-form-urlencoded:
                schema:
                  type: object
                  properties:
                    login_id:
                      type: string
                      description: Your CurrencyCloud login ID
                    api_key:
                      type: string
                      description: Your CurrencyCloud API key
                  required:
                    - login_id
                    - api_key
          responses:
            '200':
              description: Successful login, returns auth token
            '401':
              description: Invalid credentials or unauthorized access
