apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: currencycloud-logout
  description: CurrencyCloud Close Session API using X-Auth-Token header
  tags:
    - auth
    - logout
    - currencycloud
spec:
  type: openapi
  lifecycle: production
  owner: your-team
  definition: |
    openapi: 3.0.0
    info:
      title: CurrencyCloud Close Session API
      version: 1.0.0
    paths:
      /v2/authenticate/close_session:
        post:
          summary: Ends the current authenticated session
          parameters:
            - name: X-Auth-Token
              in: header
              required: true
              description: Authentication token issued at login
              schema:
                type: string
          responses:
            '200':
              description: Session closed successfully
            '401':
              description: Invalid or expired token
definition: |
  openapi: 3.0.0
  info:
    title: CurrencyCloud Login API
    version: 1.0.0
  servers:
    - url: https://devapi.currencycloud.com
  paths:
    /v2/authenticate/api:
      post:
        summary: Authenticate via login_id and api_key
        requestBody:
          required: true
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  login_id:
                    type: string
                  api_key:
                    type: string
                required:
                  - login_id
                  - api_key
        responses:
          '200':
            description: Successful login
          '401':
            description: Invalid credentials
